linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - exhaustive
    - gocritic
    - goconst
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
