name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        go: ['stable', 'oldstable']
        os: [ubuntu-latest, macos-latest]

    name: Lint & test code.
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - run: go vet ./...

      - run: go test -v -race -cover ./...
