name: CI

on:
  push:
    branches:
      - main

    tags:
      - "v*.*.*"

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write
  discussions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        go: [ 'stable', 'oldstable', '1.19' ]
        os: [ ubuntu-latest, macos-latest ]

    name: Lint & test code.
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: "v1.55.2"

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v -race -cover ./...

  build:
    needs: test
    env:
      CGO_ENABLED: 0
    
    name: Build binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Build
        run: |
          gobuild() {
            env GOOS="$1" GOARCH="$2" go build -o bin/chonk_"$1"_"$2"
          }
          mkdir bin

          gobuild linux amd64
          gobuild linux arm64
          gobuild darwin amd64
          gobuild darwin amd64
          gobuild windows amd64

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: bin/*

      - name: Update Github release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          generate_release_notes: true
          files: bin/*

  download_test:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [ test, build ]

    name: Download files
    runs-on: ubuntu-latest
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run download test
        run: env CHONK=./bin/chonk_linux_amd64 bash test.sh
