name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        go: ['stable', 'oldstable']
        os: [ubuntu-latest, macos-latest]

    name: Lint & test code.
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: "v1.55.2"

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -v -race -cover ./...
