name: Releases

on:
  release:
    types: [created]

permissions:
  contents: write
  discussions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    env:
      CGO_ENABLED: 0
    
    name: Build binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build
        run: |
          gobuild() {
            env GOOS="$1" GOARCH="$2" go build -o bin/chonk_"$1"_"$2"
          }
          mkdir bin

          gobuild linux amd64
          gobuild linux arm64
          gobuild darwin amd64
          gobuild darwin arm64
          gobuild windows amd64

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: bin/*

      - name: Update Github release
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          generate_release_notes: true
          files: bin/*

  download_test:
    needs: build

    name: Download files
    runs-on: ubuntu-latest
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4

      - run: ls -R

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run download test
        run: env CHONK=./bin/chonk_linux_amd64 bash test.sh
