name: Releases

on:
  release:
    types: [created]

permissions:
  contents: write
  discussions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CGO_ENABLED: 0

jobs:
  build:
    env:
      VERSION: ${{ github.event.release.tag_name }}

    name: Build binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5

      - name: Build
        shell: bash
        run: ./build.sh

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: bin
          path: bin/*

      - name: Update Github release
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          generate_release_notes: true
          files: bin/*

  download_test:
    name: Download files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5

      - name: Run download test
        shell: bash
        run: test.sh

      - name: Update Github release
        uses: softprops/action-gh-release@v1
        with:
          files: tests/*profile.html
